spring:
  datasource:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    resources:
      query: graphiql/query.graphql
      defaultQuery: graphiql/query.graphql
#      variables: variables.graphql
      variables: graphql/author.graphqls
    variables:
      editorTheme: solarized light
  headers:
    Authorization: Bearer <your-token>
altair:
  mapping: /altair
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: Altair
  cdn:
    enabled: false
    version: 2.1.7
  props:
    resources:
      defaultQuery: graphiql/query.graphql
      variables: graphql/author.graphqls
  headers:
    Authorization: Bearer <your-token>
graphql.playground:
  mapping: /playground
  endpoint: /graphql
  subscriptionsEndpoint: /subscriptions
  staticFolder.basePath: my-playground-resources-folder
  enabled: true
  pageTitle: Playground
  cdn:
    enabled: false
    version: latest
  settings:
    editor.cursorShape: line
    editor.fontFamily: '''Source Code Pro'', ''Consolas'', ''Inconsolata'', ''Droid
      Sans Mono'', ''Monaco'', monospace'
    editor.fontSize: 14
    editor.reuseHeaders: true
    editor.theme: dark
    general.betaUpdates: false
    prettier.printWidth: 80
    prettier.tabWidth: 2
    prettier.useTabs: false
    request.credentials: omit
    schema.polling.enable: true
    schema.polling.endpointFilter: '*localhost*'
    schema.polling.interval: 2000
    schema.disableComments: true
    tracing.hideTracingResponse: true
  headers:
    headerFor: AllTabs
  tabs:
  - name: Example Tab
    query: classpath:exampleQuery.graphql
    headers:
      SomeHeader: Some value
    variables: classpath:variables.json
    responses:
    - classpath:exampleResponse1.json
    - classpath:exampleResponse2.json